
CREATE DATABASE LibraryDB
GO

USE LibraryDB;

-- CREATE TABLES
CREATE TABLE LIBRARY_BRANCH(
	Branch_ID INT PRIMARY KEY NOT NULL IDENTITY (1,1),
	Branch_Name VARCHAR(50) NOT NULL,
	Branch_Address VARCHAR(50) NOT NULL
);
SELECT * FROM LIBRARY_BRANCH;

CREATE TABLE BOOK_COPIES(
	Book_ID INT NOT NULL,
	Branch_ID INT NOT NULL,
	Number_Of_Copies VARCHAR(50) NOT NULL
);
SELECT * FROM BOOK_COPIES;

CREATE TABLE BOOKS(
	Book_ID INT PRIMARY KEY IDENTITY (100,1),
	Title VARCHAR(50) NOT NULL,
	Publisher_Name VARCHAR(50) NOT NULL,
);
SELECT * FROM BOOKS;

CREATE TABLE BOOK_AUTHORS(
	Book_ID INT NOT NULL,
	Author_Name VARCHAR(50) NOT NULL
);
SELECT * FROM BOOK_AUTHORS;

CREATE TABLE BORROWER(
	Card_No INT PRIMARY KEY NOT NULL IDENTITY (500,1),
	Name VARCHAR(50) NOT NULL,
	Borrower_Address VARCHAR(50) NOT NULL,
	Borrower_Phone VARCHAR(50) NOT NULL,
);
SELECT * FROM BORROWER;

CREATE TABLE BOOK_LOANS(
	Book_ID INT NOT NULL,
	Branch_ID INT NOT NULL,
	Card_No INT NOT NULL,
	DateOut DATE NOT NULL,
	DateDue DATE NOT NULL
);
SELECT * FROM BOOK_LOANS;

CREATE TABLE PUBLISHER(
	Publisher_Name VARCHAR(50) PRIMARY KEY NOT NULL,
	Publisher_Address VARCHAR(50) NOT NULL,
	Phone VARCHAR(50) NOT NULL
);
SELECT * FROM PUBLISHER;

-- ALTER for Foreign Keys
ALTER TABLE BOOK_COPIES
ADD FOREIGN KEY (Book_ID) REFERENCES BOOKS(Book_ID);
ALTER TABLE BOOK_COPIES
ADD FOREIGN KEY (Branch_ID) REFERENCES LIBRARY_BRANCH(Branch_ID);

ALTER TABLE BOOKS
ADD FOREIGN KEY (Publisher_Name) REFERENCES Publisher(Publisher_Name);

ALTER TABLE BOOK_AUTHORS
ADD FOREIGN KEY (Book_ID) REFERENCES BOOKS(Book_ID);

ALTER TABLE BOOK_LOANS
ADD FOREIGN KEY (Book_ID) REFERENCES BOOKS(Book_ID);
ALTER TABLE BOOK_LOANS
ADD FOREIGN KEY (Branch_ID) REFERENCES LIBRARY_BRANCH(Branch_ID);
ALTER TABLE BOOK_LOANS
ADD FOREIGN KEY (Card_No) REFERENCES BORROWER(Card_No);


-- ADD DATA IN

